/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Add this type declaration to fix the ImportMeta error
interface ImportMetaEnv {
	VITE_FUNCTIONS_BASE?: string;
	DEV?: boolean;
}

interface ImportMeta {
	env: ImportMetaEnv;
}

export const projectId = "ibumptwkzlkniqcqmgvx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlidW1wdHdremxrbmlxY3FtZ3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4NjgwMDAsImV4cCI6MjA3OTQ0NDAwMH0.4J42sm50-i4C801YcW4Eb5WyPM5xBN3xaZ_iu9QpzVY"

// functionsBase resolves to a local relative proxy during development so the
// frontend can call the local Hono server via the Vite proxy. In production it
// points to your Supabase project's functions URL.
// Allow overriding the functions base via Vite env var `VITE_FUNCTIONS_BASE`.
// This makes it easier to point the frontend to deployed functions without
// changing code (set VITE_FUNCTIONS_BASE in an .env file or your shell).
const envOverride = (import.meta as any).env?.VITE_FUNCTIONS_BASE;
export const functionsBase = envOverride
	? envOverride
	: (import.meta as any).env?.DEV
		? '/functions/v1/make-server-8a3943bb'
		: `https://${projectId}.supabase.co/functions/v1/make-server-8a3943bb`;